import type { SanitizedCouponPluginOptions } from "../types";

export const pushTypeScriptProperties = ({
  pluginConfig,
  jsonSchema,
}: {
  pluginConfig: SanitizedCouponPluginOptions;
  jsonSchema: any;
}): any => {
  const propertiesMap = [
    ["coupons", pluginConfig.collections.couponsSlug],
    ["referralPrograms", pluginConfig.collections.referralProgramsSlug],
    ["referralCodes", pluginConfig.collections.referralCodesSlug],
  ];

  const requiredCollectionProperties = propertiesMap.map(([key]) => key);

  jsonSchema.properties.couponPlugin = {
    type: "object",
    additionalProperties: false,
    description: "Generated by the Payload Coupon plugin",
    properties: {
      collections: {
        type: "object",
        additionalProperties: false,
        properties: Object.fromEntries(propertiesMap),
        required: requiredCollectionProperties,
      },
    },
    required: ["collections"],
  };

  return jsonSchema;
};
